#!/bin/bash
# Sentinel Intelligence Hub Deployment Script
# 優化版：支援 README.md 自動更新、詳細 Git 紀錄與自動化部署

REPO_NAME="sentinel-intelligence-hub"
HUB_DIR="/Users/user/reports/hub"
GITHUB_USER="gaskhuang"
BASE_URL="https://$GITHUB_USER.github.io/$REPO_NAME"

# 1. 確保目錄與 Git 初始化
mkdir -p "$HUB_DIR/reports"
mkdir -p "$HUB_DIR/dashboard"
cd "$HUB_DIR"

if [ ! -d ".git" ]; then
    echo "📦 初始化本地 Hub 倉庫..."
    git init
    git remote add origin "https://github.com/$GITHUB_USER/$REPO_NAME.git"
fi

# 嘗試同步遠端
git pull origin main --rebase 2>/dev/null || echo "⚠️ 遠端尚未建立或分支為空"

# 2. 參數處理
# 用法: ./deploy_to_hub.sh <來源檔案路徑> <分類: daily|weekly|dashboard> <日期: YYYY-MM-DD> <標題>
SOURCE_FILE=$1
CATEGORY=$2
DATE_FOLDER=$3
TITLE=$4

if [ -z "$SOURCE_FILE" ]; then
    echo "ℹ️ 無新檔案傳入，僅執行索引更新與推送。"
else
    # 轉換為絕對路徑
    if [[ ! "$SOURCE_FILE" = /* ]]; then
        SOURCE_FILE="$(pwd)/$SOURCE_FILE"
    fi

    if [ ! -f "$SOURCE_FILE" ]; then
        echo "❌ 錯誤：來源檔案不存在 ($SOURCE_FILE)"
    else
        TARGET_SUBDIR=""
        FILENAME=$(basename "$SOURCE_FILE")

        if [ "$CATEGORY" == "daily" ]; then
            TARGET_SUBDIR="reports/$DATE_FOLDER"
        elif [ "$CATEGORY" == "weekly" ]; then
            TARGET_SUBDIR="reports/$DATE_FOLDER"
        elif [ "$CATEGORY" == "dashboard" ]; then
            TARGET_SUBDIR="dashboard"
            FILENAME="index.html"
        else
            TARGET_SUBDIR="reports/misc"
        fi

        mkdir -p "$HUB_DIR/$TARGET_SUBDIR"
        cp -r "$SOURCE_FILE" "$HUB_DIR/$TARGET_SUBDIR/$FILENAME"
        
        # 如果是 dashboard，還需要拷貝 assets
        if [ "$CATEGORY" == "dashboard" ] && [ -d "/Users/user/reports/dashboard/assets" ]; then
            cp -r /Users/user/reports/dashboard/assets "$HUB_DIR/dashboard/"
        fi
        
        echo "✅ 檔案已就緒: $TARGET_SUBDIR/$FILENAME"
    fi
fi

# 3. 重新生成 index.html (網頁版列表)
echo "🔄 更新 index.html..."
LIST_HTML=""
for f in $(find reports -name "*.html" | sort -r); do
    d=$(basename $(dirname $f))
    name=$(basename $f)
    LIST_HTML="${LIST_HTML}<div class='item'>📅 $d - <a href='$f'>$name</a></div>"
done

cat > index.html << EOF
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <title>Sentinel Intelligence Hub</title>
    <style>
        body { font-family: -apple-system, sans-serif; background: #0b0f1a; color: white; padding: 50px; line-height: 1.6; }
        h1 { color: #38bdf8; border-bottom: 1px solid #334155; padding-bottom: 10px; }
        .list { margin-top: 20px; }
        .item { background: #1e293b; margin-bottom: 10px; padding: 15px; border-radius: 8px; border: 1px solid #334155; }
        a { color: #38bdf8; text-decoration: none; font-weight: bold; }
        .dashboard-btn { display: inline-block; background: #6366f1; color: white; padding: 10px 20px; border-radius: 5px; margin-bottom: 30px; }
    </style>
</head>
<body>
    <h1>🛰️ Sentinel Intelligence Hub</h1>
    <a href="dashboard/index.html" class="dashboard-btn">🖥️ 開啟數位指揮中心</a>
    <h2>📋 歷史情報存檔</h2>
    <div class="list">
        $LIST_HTML
    </div>
    <div style="margin-top: 50px; color: #64748b; font-size: 0.8rem;">
        Last updated: $(date '+%Y-%m-%d %H:%M:%S') | 🦞 Generated by 阿蓋小弟
    </div>
</body>
</html>
EOF

# 4. 重新生成 README.md (GitHub 版列表)
echo "📝 更新 README.md..."
LIST_MD=""
for f in $(find reports -name "*.html" | sort -r); do
    d=$(basename $(dirname $f))
    name=$(basename $f)
    # 建立 GitHub 上的連結
    LIST_MD="${LIST_MD}- **$d** | [$name]($BASE_URL/$f)\n"
done

cat > README.md << EOF
# 🛰️ Sentinel Intelligence Hub

G大專屬的數位情報與自動化報告中心。

## 🖥️ 數位指揮中心
[👉 點擊開啟即時看板]($BASE_URL/dashboard/index.html)

## 📋 歷史情報報告清單
這裡記錄了所有由阿蓋小弟自動產出的情報報表，點選網址即可連結：

| 日期 | 報告題目 | 在線連結 |
| :--- | :--- | :--- |
$(find reports -name "*.html" | sort -r | while read f; do
    d=$(basename $(dirname $f))
    name=$(basename $f)
    echo "| $d | $name | [點此開啟]($BASE_URL/$f) |"
done)

---
### 🤖 系統狀態
- **維護者**: 阿蓋小弟 (OpenClaw Agent)
- **更新頻率**: 每 30 分鐘自動監控，每日 6 次定期報告
- **最後更新時間**: $(date '+%Y-%m-%d %H:%M:%S')

---
🦞 *Powered by OpenClaw & G大 AI 戰略團隊*
EOF

# 5. 詳細的 Git 提交
echo "🚀 準備推送至 GitHub..."
git add .

# 建立詳細的 commit 訊息
COMMIT_MSG="feat: Auto deploy intelligence report\n\n- Date: $(date '+%Y-%m-%d %H:%M:%S')\n- Action: Hub Index & README update"
if [ ! -z "$TITLE" ]; then
    COMMIT_MSG="$COMMIT_MSG\n- New Report: $TITLE ($DATE_FOLDER)"
fi
COMMIT_MSG="$COMMIT_MSG\n\nGenerated by 阿蓋小弟 🦞"

echo -e "$COMMIT_MSG" | git commit -F -

# 推送
git push origin main

echo "✅ GitHub 同步完成！"
echo "🌐 網址: $BASE_URL/"
